# This GitHub Actions workflow is named "ActionLint".
# It is triggered on push events and manually via the workflow_dispatch event.
#
# Permissions:
# - Read access to repository contents.
# - Write access to pull requests.
#
# Jobs:
# - job-1:
#   - Runs on the latest Ubuntu runner.
#   - Steps:
#     - Harden Runner: Uses the step-security/harden-runner action to audit egress policy.
#     - Checkout: Uses the actions/checkout action to check out the repository.
#     - ActionLint: Uses the devops-actions/actionlint action to lint the workflow files.
#       - Continues on error and sets the ID to action-lint.
# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
name: ActionLint
concurrency:
    group: actionlint-${{ github.ref }}
    cancel-in-progress: false
on:
    push:
        paths:
            - ".github/**"
    pull_request:
        paths:
            - ".github/**"
    workflow_dispatch:

permissions:
    contents: read
    pull-requests: write

jobs:
    job-1:
        runs-on: ubuntu-latest
        steps:
            - name: Harden Runner
              uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
              with:
                  egress-policy: audit
            - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
            - uses: devops-actions/actionlint@467e2ce19b2310e93c9ffa0b50fe31f86b5a7f23 # v0.1.10
              continue-on-error: true
              id: action-lint
              with:
                  shellcheck_opts: "-e SC2129"

            - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
              with:
                  name: actionlint-results
                  path: ${{ steps.action-lint.outputs.results-file }}
